### ISSUE TITLE
HTTPS Support & documentation

### ISSUE THREAD

**Issue by mattlawnz** [signalfx/collectd-jenkins#16]
Hi

Im really stummped as to how to get HTTPS working with this.
ITs not clear to me how to configure it with certs - and why do you even need certs here?
Why not just have the hostname be a URL with either https or http?

Currently getting these errors:

May 31 11:14:01 whaklljen01p collectd: [2019-05-31 11:14:01] Unable to get data from https://domain:8443/metrics/REDACTED_KEYl/metrics/ for metrics
May 31 11:14:01 whaklljen01p collectd: [2019-05-31 11:14:01] Error making API call (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)>) https://domain:8443/metrics/REDACTED_KEY/healthcheck/
May 31 11:14:01 whaklljen01p collectd: [2019-05-31 11:14:01] Unable to get data from https://domain:8443/metrics/REDACTED_KEY/healthcheck/ for healthcheck

Curl works no problem to the address above.

**Comment by mstumpfx** [comment]
Hey @mattlawnz 

Are you using the standalone collectd plugin or the SignalFx Smart Agent? We encourage users to use the the agent these days.

I believe one of your teammates also opened up a support ticket with our support team regarding the jenkins plugin. I would recommend you do the same, as you will probably get a faster resolution that route.

Anyway, the certs are optional and if not provided it looks like the client will try to connect via HTTP. 
https://github.com/signalfx/collectd-jenkins/blob/master/jenkins.py#L161
https://github.com/signalfx/collectd-jenkins/blob/master/urllib_auth_n_ssl_handler.py#L11

What configuration are you passing through to collectd?

**Comment by mattlawnz** [comment]
Hi

We are using the mart agent at present.
Yes, I see the ticket as well, and we were asked to create a self signed cert to test with.


this is our collectd jenkins config:

```
LoadPlugin python
<Plugin python>
    ModulePath "/usr/share/collectd/collectd-jenkins"
    Import jenkins
    <Module jenkins>
        Host "jenkins-ibm.domain"
        Port "8443"
        Username "303429"
        APIToken "REDACTED"
        MetricsKey "REDACTED"
        VerifyPeer "false"
        ssl_keyfile "/etc/ssl/certs/jenkins.key"
        ssl_certificate "/etc/ssl/certs/jenkins.crt"
        ssl_ca_certs "/etc/ssl/certs/comodo.ca-bundle"
        Interval 10
    </Module>
</Plugin>
```

As mentioned before, If we curl the URL then we dont get any issues.
I'll continue to work with support  on this as well.

**Comment by buuren** [comment]
This should be already resolved in release https://github.com/signalfx/signalfx-agent/releases/tag/v4.11.1

Here a yaml config snippet which worked for me:

`    - type: collectd/jenkins
      host: jenkins.yourdomain.com
      port: 443
      metricsKey: metrics
      useHTTPS: true
      enhancedMetrics: true
`
