### ISSUE TITLE
Leaks api token into logs

### ISSUE THREAD

**Issue by RogerWatkins-Anaplan** [signalfx/collectd-jenkins#36]
Description:

SignalFX agent is deployed to kubernetes with collectd-jenkins used to scrape metrics from Jenkins. It is using image `quay.io/signalfx/signalfx-agent:5.10.2`.

Issue:
Logs shown below with the api key output in cleartext.

`time="2022-02-07T15:41:31Z" level=info msg="Using username 'my-username' and api_token 'my_secret_token' " createdTime=1.6442484915934362e+09 lineno=269 logger=root monitorID=13 monitorType=collectd/jenkins runnerPID=35 sourcePath=/collectd-python/jenkins/jenkins.py`

If you are using splunk forwarder to monitor these logs then these are leaked into splunk as well.

**Comment by rmfitzpatrick** [comment]
The fix for this was incorporated in https://github.com/signalfx/signalfx-agent/releases/tag/v5.19.0.
